print("Hello, World!")
print("你好，世界！")
print("¡Hola, Mundo!")
print("Bonjour, le monde!") 
print("Hallo, Welt!")
print("Ciao, mondo!")
print("Olá, Mundo!")
print("Привет, мир!")
print("こんにちは、世界！")
print("안녕하세요, 세계!")
